/**
 * Intent classification — 100 prompt test suite.
 * Generated by 10 parallel agents, one domain each.
 * Run: pnpm test src/__tests__/intent-100-classify.test.ts
 */
import { describe, it, expect, afterAll } from "vitest";

const savedRequireLlm = process.env.OMNISTATE_REQUIRE_LLM;
const savedApiKey = process.env.ANTHROPIC_API_KEY;
const savedRouter9Key = process.env.OMNISTATE_ROUTER9_API_KEY;
process.env.OMNISTATE_REQUIRE_LLM = "false";
delete process.env.ANTHROPIC_API_KEY;
delete process.env.OMNISTATE_ROUTER9_API_KEY;

import { classifyIntent } from "../planner/intent.js";

afterAll(() => {
  if (savedRequireLlm !== undefined) process.env.OMNISTATE_REQUIRE_LLM = savedRequireLlm;
  else delete process.env.OMNISTATE_REQUIRE_LLM;
  if (savedApiKey !== undefined) process.env.ANTHROPIC_API_KEY = savedApiKey;
  if (savedRouter9Key !== undefined) process.env.OMNISTATE_ROUTER9_API_KEY = savedRouter9Key;
});

// ─── AGENT 1: Siri-class + audio/media ────────────────────────────────────
describe("AGENT 1: Siri-class + audio/media", () => {
  it("set timer 5 minutes", async () => {
    const r = await classifyIntent("set timer 5 minutes");
    expect(r.type).not.toBe("shell-command");
    expect(["alarm.set", "app-control", "multi-step"]).toContain(r.type);
  });

  it("đặt báo thức 7 giờ sáng", async () => {
    const r = await classifyIntent("đặt báo thức 7 giờ sáng");
    expect(["alarm.set", "app-control", "multi-step"]).toContain(r.type);
  });

  it("đợi 30 giây", async () => {
    const r = await classifyIntent("đợi 30 giây");
    expect(r.type).toBe("alarm.set");
  });

  it("bật nhạc lên", async () => {
    const r = await classifyIntent("bật nhạc lên");
    expect(["media.play", "audio-management", "app-control", "multi-step"]).toContain(r.type);
  });

  it("tắt nhạc đi", async () => {
    const r = await classifyIntent("tắt nhạc đi");
    expect(["media.pause", "audio-management", "app-control"]).toContain(r.type);
  });

  it("bài tiếp theo", async () => {
    const r = await classifyIntent("bài tiếp theo");
    expect(["app-control", "media.nextTrack", "audio-management"]).toContain(r.type);
  });

  it("ghi chú: mua sữa ngày mai", async () => {
    const r = await classifyIntent("ghi chú: mua sữa ngày mai");
    expect(["app-control", "file-operation", "multi-step"]).toContain(r.type);
  });

  it("tạo reminder: họp lúc 3 giờ", async () => {
    const r = await classifyIntent("tạo reminder: họp lúc 3 giờ");
    expect(["app-control", "alarm.set", "multi-step"]).toContain(r.type);
  });

  it("xem lịch hôm nay", async () => {
    const r = await classifyIntent("xem lịch hôm nay");
    expect(["app-control", "system-query", "multi-step"]).toContain(r.type);
  });

  it("tăng âm lượng lên 80%", async () => {
    const r = await classifyIntent("tăng âm lượng lên 80%");
    expect(["audio-management", "app-control", "hardware-control"]).toContain(r.type);
  });
});

// ─── AGENT 2: System query + process/service ──────────────────────────────
describe("AGENT 2: System query + process/service", () => {
  it("làm gì được với máy này", async () => {
    const r = await classifyIntent("làm gì được với máy này");
    expect(r.type).toBe("system-query");
  });

  it("máy tôi chạy ổn không", async () => {
    const r = await classifyIntent("máy tôi chạy ổn không");
    expect(r.type).toBe("system-query");
  });

  it("kiểm tra pin còn bao nhiêu", async () => {
    const r = await classifyIntent("kiểm tra pin còn bao nhiêu");
    expect(["power-management", "system-query", "health-check"]).toContain(r.type);
  });

  it("list running processes", async () => {
    const r = await classifyIntent("list running processes");
    expect(["process-management", "system-query"]).toContain(r.type);
  });

  it("kill process named node", async () => {
    const r = await classifyIntent("kill process named node");
    expect(r.type).toBe("process-management");
  });

  it("restart docker service", async () => {
    const r = await classifyIntent("restart docker service");
    expect(["service-management", "container-management", "shell-command"]).toContain(r.type);
  });

  it("kiểm tra mạng internet", async () => {
    const r = await classifyIntent("kiểm tra mạng internet");
    expect(["system-query", "network-control", "health-check"]).toContain(r.type);
  });

  it("how long has the system been running", async () => {
    const r = await classifyIntent("how long has the system been running");
    expect(r.type).toBe("system-query");
  });

  it("cho tôi xem CPU usage", async () => {
    const r = await classifyIntent("cho tôi xem CPU usage");
    expect(["system-query", "process-management"]).toContain(r.type);
  });

  it("dùng bao nhiêu RAM rồi", async () => {
    const r = await classifyIntent("dùng bao nhiêu RAM rồi");
    expect(["memory-management", "system-query"]).toContain(r.type);
  });
});

// ─── AGENT 3: File operations + disk/memory ────────────────────────────────
describe("AGENT 3: File operations + disk/memory", () => {
  it("mở file test.txt", async () => {
    const r = await classifyIntent("mở file test.txt");
    expect(r.type).toBe("file-operation");
  });

  it("tạo thư mục project mới", async () => {
    const r = await classifyIntent("tạo thư mục project mới");
    expect(r.type).toBe("file-operation");
  });

  it("copy file này sang desktop", async () => {
    const r = await classifyIntent("copy file này sang desktop");
    expect(r.type).toBe("file-operation");
  });

  it("xóa file temp.log", async () => {
    const r = await classifyIntent("xóa file temp.log");
    expect(r.type).toBe("file-operation");
  });

  it("tìm kiếm file có đuôi .log", async () => {
    const r = await classifyIntent("tìm kiếm file có đuôi .log");
    expect(["file.search", "file-operation", "system-query"]).toContain(r.type);
  });

  it("nén file đó lại", async () => {
    const r = await classifyIntent("nén file đó lại");
    expect(r.type).toBe("file-operation");
  });

  it("giải nén archive.zip", async () => {
    const r = await classifyIntent("giải nén archive.zip");
    expect(r.type).toBe("file-operation");
  });

  it("disk usage còn bao nhiêu", async () => {
    const r = await classifyIntent("disk usage còn bao nhiêu");
    expect(["disk-management", "system-query"]).toContain(r.type);
  });

  it("find large files bigger than 1GB", async () => {
    const r = await classifyIntent("find large files bigger than 1GB");
    expect(["disk-cleanup", "file-operation", "system-query"]).toContain(r.type);
  });

  it("mở thư mục Downloads", async () => {
    const r = await classifyIntent("mở thư mục Downloads");
    expect(r.type).toBe("file-operation");
  });
});

// ─── AGENT 4: Network + firewall + VPN + security ─────────────────────────
describe("AGENT 4: Network + firewall + VPN + security", () => {
  it("bật wifi lên", async () => {
    const r = await classifyIntent("bật wifi lên");
    expect(["network-control", "multi-step"]).toContain(r.type);
  });

  it("tắt wifi đi", async () => {
    const r = await classifyIntent("tắt wifi đi");
    expect(["network-control", "multi-step"]).toContain(r.type);
  });

  it("kết nối wifi tên là Office", async () => {
    const r = await classifyIntent("kết nối wifi tên là Office");
    expect(r.type).toBe("network-control");
  });

  it("ping google.com xem mạng có không", async () => {
    const r = await classifyIntent("ping google.com xem mạng có không");
    expect(["network-control", "system-query"]).toContain(r.type);
  });

  it("turn on firewall", async () => {
    const r = await classifyIntent("turn on firewall");
    expect(["security-management", "network-control"]).toContain(r.type);
  });

  it("show open ports", async () => {
    const r = await classifyIntent("show open ports");
    expect(["network-control", "security-management"]).toContain(r.type);
  });

  it("kết nối VPN office", async () => {
    const r = await classifyIntent("kết nối VPN office");
    expect(["network-control", "security-management"]).toContain(r.type);
  });

  it("scan wifi networks nearby", async () => {
    const r = await classifyIntent("scan wifi networks nearby");
    expect(["wifi-security", "network-control"]).toContain(r.type);
  });

  it("block IP 192.168.1.100", async () => {
    const r = await classifyIntent("block IP 192.168.1.100");
    expect(["security-management", "network-control"]).toContain(r.type);
  });

  it("check DNS settings", async () => {
    const r = await classifyIntent("check DNS settings");
    expect(["network-control", "security-management"]).toContain(r.type);
  });
});

// ─── AGENT 5: App launch/control + UI + clipboard ─────────────────────────
describe("AGENT 5: App launch/control + UI + clipboard", () => {
  it("mở Safari lên", async () => {
    const r = await classifyIntent("mở Safari lên");
    expect(["app-launch", "app-control", "multi-step"]).toContain(r.type);
  });

  it("open Notion", async () => {
    const r = await classifyIntent("open Notion");
    expect(["app-launch", "app-control"]).toContain(r.type);
  });

  it("đóng hết tất cả tab", async () => {
    const r = await classifyIntent("đóng hết tất cả tab");
    expect(["app-control", "multi-step"]).toContain(r.type);
  });

  it("tắt ứng dụng này đi", async () => {
    const r = await classifyIntent("tắt ứng dụng này đi");
    expect(["app-control", "app-launch"]).toContain(r.type);
  });

  it("chụp màn hình rồi gửi qua Zalo", async () => {
    const r = await classifyIntent("chụp màn hình rồi gửi qua Zalo");
    expect(r.type).toBe("multi-step");
  });

  it("click vào nút đăng nhập", async () => {
    const r = await classifyIntent("click vào nút đăng nhập");
    expect(r.type).toBe("ui-interaction");
  });

  it("type password vào form", async () => {
    const r = await classifyIntent("type password vào form");
    expect(["ui-interaction", "security-management"]).toContain(r.type);
  });

  it("copy nội dung vào clipboard", async () => {
    const r = await classifyIntent("copy nội dung vào clipboard");
    expect(["clipboard-management", "ui-interaction"]).toContain(r.type);
  });

  it("paste từ clipboard", async () => {
    const r = await classifyIntent("paste từ clipboard");
    expect(["clipboard-management", "ui-interaction"]).toContain(r.type);
  });

  it("scroll xuống dưới", async () => {
    const r = await classifyIntent("scroll xuống dưới");
    expect(r.type).toBe("ui-interaction");
  });
});

// ─── AGENT 6: Package management + developer tools ───────────────────────────
describe("AGENT 6: Package management + developer tools", () => {
  it("brew install node", async () => {
    const r = await classifyIntent("brew install node");
    expect(r.type).toBe("package-management");
  });

  it("cài đặt package bằng npm", async () => {
    const r = await classifyIntent("cài đặt package bằng npm");
    expect(r.type).toBe("package-management");
  });

  it("pip install requests", async () => {
    const r = await classifyIntent("pip install requests");
    expect(r.type).toBe("package-management");
  });

  it("uninstall chrome via brew", async () => {
    const r = await classifyIntent("uninstall chrome via brew");
    expect(["package-management", "update-management"]).toContain(r.type);
  });

  it("check npm outdated", async () => {
    const r = await classifyIntent("check npm outdated");
    expect(["package-management", "update-management"]).toContain(r.type);
  });

  it("run npm start", async () => {
    const r = await classifyIntent("run npm start");
    expect(["shell-command", "package-management"]).toContain(r.type);
  });

  it("search for python package pandas", async () => {
    const r = await classifyIntent("search for python package pandas");
    expect(["package-management", "system-query"]).toContain(r.type);
  });

  it("upgrade all brew packages", async () => {
    const r = await classifyIntent("upgrade all brew packages");
    expect(r.type).toBe("package-management");
  });

  it("list installed npm packages", async () => {
    const r = await classifyIntent("list installed npm packages");
    expect(["package-management", "system-query"]).toContain(r.type);
  });

  it("cài thư viện react cho project", async () => {
    const r = await classifyIntent("cài thư viện react cho project");
    expect(r.type).toBe("package-management");
  });
});

// ─── AGENT 7: Hardware + display + bluetooth + keyboard ─────────────────────
describe("AGENT 7: Hardware + display + bluetooth + keyboard", () => {
  it("tăng độ sáng màn hình lên", async () => {
    const r = await classifyIntent("tăng độ sáng màn hình lên");
    expect(["display-management", "hardware-control"]).toContain(r.type);
  });

  it("giảm độ sáng xuống", async () => {
    const r = await classifyIntent("giảm độ sáng xuống");
    expect(["display-management", "hardware-control"]).toContain(r.type);
  });

  it("bật bluetooth lên", async () => {
    const r = await classifyIntent("bật bluetooth lên");
    expect(["peripheral-management", "hardware-control"]).toContain(r.type);
  });

  it("turn off bluetooth", async () => {
    const r = await classifyIntent("turn off bluetooth");
    expect(["peripheral-management", "hardware-control"]).toContain(r.type);
  });

  it("list bluetooth devices", async () => {
    const r = await classifyIntent("list bluetooth devices");
    expect(["peripheral-management", "system-query"]).toContain(r.type);
  });

  it("đổi keyboard layout sang tiếng Việt", async () => {
    const r = await classifyIntent("đổi keyboard layout sang tiếng Việt");
    expect(["hardware-control", "os-config"]).toContain(r.type);
  });

  it("print document hello.pdf", async () => {
    const r = await classifyIntent("print document hello.pdf");
    expect(["printer-management", "hardware-control"]).toContain(r.type);
  });

  it("battery health check", async () => {
    const r = await classifyIntent("battery health check");
    expect(["power-management", "health-check", "iokit-hardware"]).toContain(r.type);
  });

  it("sleep máy ngay", async () => {
    const r = await classifyIntent("sleep máy ngay");
    expect(["power-management", "hardware-control"]).toContain(r.type);
  });

  it("restart máy tính", async () => {
    const r = await classifyIntent("restart máy tính");
    expect(["power-management", "hardware-control"]).toContain(r.type);
  });
});

// ─── AGENT 8: Container + VM + kernel + IOKit + WiFi security ─────────────
describe("AGENT 8: Container + VM + kernel + IOKit + WiFi security", () => {
  it("docker ps", async () => {
    const r = await classifyIntent("docker ps");
    expect(["container-management", "shell-command"]).toContain(r.type);
  });

  it("stop all containers", async () => {
    const r = await classifyIntent("stop all containers");
    expect(["container-management", "shell-command"]).toContain(r.type);
  });

  it("docker compose up -d", async () => {
    const r = await classifyIntent("docker compose up -d");
    expect(["container-management", "shell-command"]).toContain(r.type);
  });

  it("show container logs", async () => {
    const r = await classifyIntent("show container logs");
    expect(["container-management", "shell-command"]).toContain(r.type);
  });

  it("read SMC keys for temperature", async () => {
    const r = await classifyIntent("read SMC keys for temperature");
    expect(r.type).toBe("iokit-hardware");
  });

  it("đọc nhiệt độ CPU qua IOKit", async () => {
    const r = await classifyIntent("đọc nhiệt độ CPU qua IOKit");
    expect(r.type).toBe("iokit-hardware");
  });

  it("kernel sysctl net.inet.tcp.timestamps", async () => {
    const r = await classifyIntent("kernel sysctl net.inet.tcp.timestamps");
    expect(r.type).toBe("kernel-control");
  });

  it("check kernel extension status", async () => {
    const r = await classifyIntent("check kernel extension status");
    expect(["kernel-control", "system-query"]).toContain(r.type);
  });

  it("launchctl list | grep agent", async () => {
    const r = await classifyIntent("launchctl list | grep agent");
    expect(["kernel-control", "shell-command"]).toContain(r.type);
  });

  it("capture wifi handshake nearby", async () => {
    const r = await classifyIntent("capture wifi handshake nearby");
    expect(["wifi-security", "network-control"]).toContain(r.type);
  });
});

// ─── AGENT 9: Hybrid workflows + automation + learning ─────────────────────
describe("AGENT 9: Hybrid workflows + automation + learning", () => {
  it("gửi tin nhắn cho An trên Zalo", async () => {
    const r = await classifyIntent("gửi tin nhắn cho An trên Zalo");
    expect(["app-control", "multi-step"]).toContain(r.type);
  });

  it("send file qua Telegram cho Nam", async () => {
    const r = await classifyIntent("send file qua Telegram cho Nam");
    expect(["app-control", "multi-step"]).toContain(r.type);
  });

  it("open youtube and search for jazz music", async () => {
    const r = await classifyIntent("open youtube and search for jazz music");
    expect(r.type).toBe("multi-step");
  });

  it("mở video 'chill music' trên youtube", async () => {
    const r = await classifyIntent("mở video 'chill music' trên youtube");
    expect(r.type).toBe("multi-step");
  });

  it("orchestrate app switching between Slack and Notion", async () => {
    const r = await classifyIntent("orchestrate app switching between Slack and Notion");
    expect(["multi-app-orchestration", "app-control", "multi-step"]).toContain(r.type);
  });

  it("bật nhạc rồi đợi 10 phút tắt máy", async () => {
    const r = await classifyIntent("bật nhạc rồi đợi 10 phút tắt máy");
    expect(r.type).toBe("multi-step");
  });

  it("run data entry workflow for csv file", async () => {
    const r = await classifyIntent("run data entry workflow for csv file");
    expect(["workflow.dataEntry", "multi-step"]).toContain(r.type);
  });

  it("generate script to backup documents", async () => {
    const r = await classifyIntent("generate script to backup documents");
    expect(["script-generation", "backup-restore", "multi-step"]).toContain(r.type);
  });

  it("tạo automation macro cho email", async () => {
    const r = await classifyIntent("tạo automation macro cho email");
    expect(["automation-macro", "multi-step"]).toContain(r.type);
  });

  it("run workflow template for meeting prep", async () => {
    const r = await classifyIntent("run workflow template for meeting prep");
    expect(["workflow-template", "workflow.meeting", "multi-step"]).toContain(r.type);
  });
});

// ─── AGENT 10: Non-technical Vietnamese + edge cases ───────────────────────
describe("AGENT 10: Non-technical Vietnamese + edge cases", () => {
  it("mở app giúp tôi", async () => {
    const r = await classifyIntent("mở app giúp tôi");
    expect(r.type).toBe("ask-clarification");
  });

  it("tắt máy giúp tôi", async () => {
    const r = await classifyIntent("tắt máy giúp tôi");
    expect(r.type).toBe("ask-clarification");
  });

  it("dịch đoạn này sang tiếng Anh", async () => {
    const r = await classifyIntent("dịch đoạn này sang tiếng Anh");
    expect(r.type).toBe("ask-clarification");
  });

  it("xoá hết tất cả file trong thư mục temp", async () => {
    const r = await classifyIntent("xoá hết tất cả file trong thư mục temp");
    expect(["ask-clarification", "file-operation"]).toContain(r.type);
  });

  it("chế độ tối bật lên", async () => {
    const r = await classifyIntent("chế độ tối bật lên");
    expect(["os-config", "display-management"]).toContain(r.type);
  });

  it("bật chế độ tập trung", async () => {
    const r = await classifyIntent("bật chế độ tập trung");
    expect(["os-config", "system-query"]).toContain(r.type);
  });

  it("tắt chế độ tập trung đi", async () => {
    const r = await classifyIntent("tắt chế độ tập trung đi");
    expect(["os-config", "system-query"]).toContain(r.type);
  });

  it("gửi email cho boss", async () => {
    const r = await classifyIntent("gửi email cho boss");
    expect(r.type).toBe("ask-clarification");
  });

  it("find TODO and FIXME in project", async () => {
    const r = await classifyIntent("find TODO and FIXME in project");
    expect(["shell-command", "file.search"]).toContain(r.type);
  });

  it("analyze error from crash log", async () => {
    const r = await classifyIntent("analyze error from crash log");
    expect(["debug-assist", "shell-command"]).toContain(r.type);
  });

  it("dọn desktop giúp tôi", async () => {
    const r = await classifyIntent("dọn desktop giúp tôi");
    expect(["file-organization", "maintenance.diskCleanup", "multi-step"]).toContain(r.type);
  });

  it("xoá cache trình duyệt Chrome", async () => {
    const r = await classifyIntent("xoá cache trình duyệt Chrome");
    expect(["app-control", "maint.clearBrowserCache"]).toContain(r.type);
  });

  it("thay đổi wallpaper", async () => {
    const r = await classifyIntent("thay đổi wallpaper");
    expect(["os-config", "app-control"]).toContain(r.type);
  });

  it("split window left and right", async () => {
    const r = await classifyIntent("split window left and right");
    expect(["app-control", "ui-interaction"]).toContain(r.type);
  });

  it("maximize window hiện tại", async () => {
    const r = await classifyIntent("maximize window hiện tại");
    expect(["app-control", "ui-interaction"]).toContain(r.type);
  });

  it("bookmark trang này", async () => {
    const r = await classifyIntent("bookmark trang này");
    expect(["app-control", "multi-step"]).toContain(r.type);
  });

  it("open history", async () => {
    const r = await classifyIntent("open history");
    expect(["app-control", "system-query"]).toContain(r.type);
  });

  it("clear browsing history", async () => {
    const r = await classifyIntent("clear browsing history");
    expect(["app-control", "multi-step"]).toContain(r.type);
  });

  it("tắt tiếng (mute) máy tính", async () => {
    const r = await classifyIntent("tắt tiếng (mute) máy tính");
    expect(["audio-management", "app-control", "hardware-control"]).toContain(r.type);
  });

  it("eject USB drive", async () => {
    const r = await classifyIntent("eject USB drive");
    expect(["hardware-control", "file-operation"]).toContain(r.type);
  });
});