import { describe, it, expect, vi } from "vitest";
import { classifyIntent } from "../planner/classify.js";

vi.mock("../llm/router.js", () => ({
  requestLlmTextWithFallback: vi.fn().mockResolvedValue({ text: '{"type":"iokit-hardware","confidence":0.9}' }),
  isLlmRequired: vi.fn().mockReturnValue(false),
  resolveEffectiveBudget: vi.fn().mockReturnValue({ maxInputChars: 2000, intentMax: 128, compactPrompt: false }),
}));

const VALID = ["iokit-hardware","kernel-control","wifi-security","hardware-control","thermal-management","power-management","peripheral-management","shell-command","system-query","ask-clarification","os-config","app-control","file-operation","app-launch","display-management","ui-interaction"];

function ok(t: string, p: string) {
  return it(t, async () => {
    const intent = await classifyIntent(p);
    expect(VALID, `"${p}" → got "${intent.type}"`).toContain(intent.type);
  });
}

describe("Agent T: Hardware & Deep OS Control (50 prompts)", () => {
  ok("read SMC keys", "read SMC keys");
  ok("đọc SMC keys", "đọc SMC keys");
  ok("SMC fan control", "SMC fan control");
  ok("kiểm soát quạt", "kiểm soát quạt");
  ok("set fan speed 2000", "set fan speed to 2000 RPM");
  ok("read battery cycle count", "read battery cycle count");
  ok("đếm cycle pin", "đếm cycle pin");
  ok("battery health percentage", "check battery health percentage");
  ok("ioreg battery info", "ioreg battery info");
  ok("IOKit hardware tree", "IOKit hardware tree");
  ok("liệt kê phần cứng", "liệt kê phần cứng");
  ok("USB device tree", "USB device tree");
  ok("pci devices", "list PCI devices");
  ok("nvram boot-args", "read nvram boot-args");
  ok("read nvram", "read nvram");
  ok("set nvram variable", "set nvram variable");
  ok("read kernel extension", "read kernel extension");
  ok("kext loaded list", "kextstat");
  ok("load kernel extension", "load kernel extension");
  ok("unload kernel extension", "unload kernel extension");
  ok("sysctl hw.model", "sysctl hw.model");
  ok("sysctl machdep.cpu", "sysctl machdep.cpu");
  ok("CPU brand string", "CPU brand string");
  ok("memory info", "memory info");
  ok("hardware UUID", "hardware UUID");
  ok("serial number", "serial number");
  ok("read hardware info", "read hardware info");
  ok("hardware serial", "hardware serial");
  ok("GPU temperature", "GPU temperature");
  ok("GPU info", "GPU info");
  ok("NVIDIA temperature", "NVIDIA temperature");
  ok("AMD temperature", "AMD temperature");
  ok("graphics card info", "graphics card info");
  ok("display EDID", "read display EDID");
  ok("read display info", "read display info");
  ok("monitor EDID data", "monitor EDID data");
  ok("USB power delivery", "USB power delivery");
  ok("Thunderbolt devices", "Thunderbolt devices");
  ok("detect external monitor", "detect external monitor");
  ok("screen gamma", "screen gamma");
  ok("color profile", "color profile");
  ok("audio device info", "audio device info");
  ok("audio input output", "audio input output");
  ok("microphone list", "list microphones");
  ok("camera list", "list cameras");
  ok("FaceTime camera", "FaceTime camera");
  ok("external camera", "external camera");
  ok("Bluetooth devices", "Bluetooth devices");
  ok("HID devices", "HID devices");
  ok("keyboard layout", "keyboard layout");
  ok("input source", "input source");
  ok("mouse speed", "mouse speed");
  ok("trackpad settings", "trackpad settings");
  ok("mouse acceleration", "mouse acceleration");
  ok("keyboard repeat", "keyboard repeat");
  ok("key binding", "key binding");
  ok("hotkey remap", "remap hotkey");
  ok("WiFi airport info", "WiFi airport info");
  ok("WiFi scan results", "WiFi scan results");
  ok("WiFi signal dBm", "WiFi signal dBm");
  ok("WiFi channel", "WiFi channel");
  ok("WiFi interference", "WiFi interference");
  ok("WiFi security type", "WiFi security type");
  ok("WiFi password lookup", "WiFi password lookup");
  ok("airport info.plist", "airport info.plist");
  ok("WiFi diagnostics", "WiFi diagnostics");
  ok("WiFi signal quality", "WiFi signal quality");
  ok("network interface", "network interface");
  ok("en0 WiFi status", "en0 WiFi status");
  ok("USB device info", "USB device info");
  ok("disk IOKit", "disk IOKit");
  ok("system serial", "system serial");
  ok("hardware warranty", "check hardware warranty");
  ok("AppleCare status", "AppleCare status");
  ok("detect hardware", "detect hardware");
  ok("hardware profile", "hardware profile");
  ok("hardware monitoring", "hardware monitoring");
  ok("GPU fan speed", "GPU fan speed");
  ok("RAM voltage", "RAM voltage");
  ok("memory slots", "memory slots");
  ok("RAM speed", "RAM speed");
  ok("SSD SMART", "SSD SMART");
  ok("NVMe temperature", "NVMe temperature");
  ok("Thunderbolt speed", "Thunderbolt speed");
  ok("USB speed", "USB speed");
  ok("sleep wake failure", "sleep wake failure");
  ok("wake from sleep", "wake from sleep");
  ok("hibernate mode", "hibernate mode");
  ok("power state", "power state");
  ok("energy consumption", "energy consumption");
  ok("power metrics", "power metrics");
  ok("battery time remaining", "battery time remaining");
  ok("charging status", "charging status");
  ok("adapter wattage", "adapter wattage");
  ok("charger type", "charger type");
  ok("MagSafe info", "MagSafe info");
  ok("wireless charging", "wireless charging");
  ok("hardware test mode", "hardware test mode");
  ok("diagnostic mode", "diagnostic mode");
  ok("Apple Hardware Test", "Apple Hardware Test");
  ok("AHT boot", "AHT boot");
  ok("reset PMU", "reset PMU");
  ok("PMU reset", "PMU reset");
  ok("SMC reset command", "SMC reset command");
  ok("ioreg dump", "ioreg dump");
  ok("iostat", "iostat");
  ok("iotop", "iotop");
  ok("ioctl calls", "ioctl calls");
  ok("disk I/O stats", "disk I/O stats");
  ok("block device info", "block device info");
  ok("mount points", "mount points");
  ok("hardware mounting", "hardware mounting");
  ok("hardware eject", "hardware eject");
  ok("unmount force", "unmount force");
  ok("kernel symbols", "kernel symbols");
  ok("dtrace script", "dtrace script");
  ok("dtruss process", "dtruss process");
  ok("system call trace", "system call trace");
  ok("strace process", "strace process");
  ok("syscall monitor", "syscall monitor");
});
