export type CapabilityStatus = "implemented" | "experimental" | "unsupported" | "flagged";

export type CapabilityRiskTier =
  | "read-only"
  | "reversible-write"
  | "destructive"
  | "system-sensitive";

export type CapabilityVerifier =
  | "vision"
  | "accessibility"
  | "app-state"
  | "dom"
  | "heuristic"
  | "api"
  | "file"
  | "process"
  | "compound";

export interface CapabilityTestCoverage {
  unit: boolean;
  integration: boolean;
  e2e: boolean;
}

export interface CapabilityPolicy {
  platform: "macos";
  stability: "public" | "privileged" | "experimental";
  requiresPrivilege: boolean;
  requiresConfirmation: boolean;
  allowedByDefault: boolean;
}

export interface CapabilityContract {
  id: string;
  label: string;
  owner: "planner" | "gateway" | "swift-app" | "web" | "native-runtime";
  status: CapabilityStatus;
  riskTier: CapabilityRiskTier;
  inputSchema: string;
  executionPath: string;
  verifier: CapabilityVerifier;
  observability: string[];
  tests: CapabilityTestCoverage;
  policy?: CapabilityPolicy;
  notes?: string;
}

export interface CapabilityMatrixEntry {
  tool: string;
  contractId: string;
  status: CapabilityStatus;
}

export const CAPABILITY_CONTRACTS: Record<string, CapabilityContract> = {
  // ─── App Lifecycle ───────────────────────────────────────────────────────
  "app.launch": {
    id: "app.launch",
    label: "Launch Or Activate App",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ name: string }",
    executionPath: "planner -> intents/app.launch -> deep/launchApp",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "app.activate": {
    id: "app.activate",
    label: "Activate Existing App (Bring to Front)",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ name: string }",
    executionPath: "planner -> intents/app.activate -> deep/activateApp",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "app.quit": {
    id: "app.quit",
    label: "Quit App",
    owner: "gateway",
    status: "implemented",
    riskTier: "destructive",
    inputSchema: "{ name: string }",
    executionPath: "planner -> intents/app.quit -> deep/quitApp",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "app.script": {
    id: "app.script",
    label: "Browser/App AppleScript Control",
    owner: "gateway",
    status: "implemented",
    riskTier: "system-sensitive",
    inputSchema: "{ script: string }",
    executionPath: "planner -> intents/app.script -> deep/runAppleScript",
    verifier: "heuristic",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
    notes: "Verification is still partially heuristic until typed browser state evidence lands.",
  },

  // ─── Browser — Tab Management ─────────────────────────────────────────────
  "browser.open": {
    id: "browser.open",
    label: "Open Browser URL",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ url: string, browser?: string }",
    executionPath: "planner -> intents/browser.open -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.newTab": {
    id: "browser.newTab",
    label: "Create Browser Tab",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ url?: string, browser?: string }",
    executionPath: "planner -> intents/browser.newTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.listTabs": {
    id: "browser.listTabs",
    label: "List Open Tabs",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.listTabs -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.getActiveTab": {
    id: "browser.getActiveTab",
    label: "Get Active Tab Metadata",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getActiveTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.switchTab": {
    id: "browser.switchTab",
    label: "Switch to Tab by Index",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ tabIndex: number, browser?: string }",
    executionPath: "planner -> intents/browser.switchTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.closeTab": {
    id: "browser.closeTab",
    label: "Close Browser Tab",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ tabIndex?: number, browser?: string }",
    executionPath: "planner -> intents/browser.closeTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.reloadTab": {
    id: "browser.reloadTab",
    label: "Reload Active Tab",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.reloadTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.duplicateTab": {
    id: "browser.duplicateTab",
    label: "Duplicate Active Tab",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.duplicateTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },

  // ─── Browser — Navigation ─────────────────────────────────────────────────
  "browser.navigateTo": {
    id: "browser.navigateTo",
    label: "Navigate to URL in Active Tab",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ url: string, browser?: string }",
    executionPath: "planner -> intents/browser.navigateTo -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.goBack": {
    id: "browser.goBack",
    label: "Navigate Back in Tab History",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.goBack -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.goForward": {
    id: "browser.goForward",
    label: "Navigate Forward in Tab History",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.goForward -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getUrl": {
    id: "browser.getUrl",
    label: "Get Active Tab URL",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getUrl -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getTitle": {
    id: "browser.getTitle",
    label: "Get Active Tab Title",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getTitle -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getPageSource": {
    id: "browser.getPageSource",
    label: "Get Page HTML Source",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getPageSource -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.executeJs": {
    id: "browser.executeJs",
    label: "Execute JavaScript in Browser",
    owner: "gateway",
    status: "implemented",
    riskTier: "system-sensitive",
    inputSchema: "{ script: string, browser?: string }",
    executionPath: "planner -> intents/browser.executeJs -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Arbitrary JS execution; risk tier reflects potential for unintended side effects.",
  },

  // ─── Browser — DOM / Element Interaction ─────────────────────────────────
  "browser.querySelector": {
    id: "browser.querySelector",
    label: "Query Single DOM Element",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ selector: string, browser?: string }",
    executionPath: "planner -> intents/browser.querySelector -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.querySelectorAll": {
    id: "browser.querySelectorAll",
    label: "Query All DOM Elements",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ selector: string, browser?: string }",
    executionPath: "planner -> intents/browser.querySelectorAll -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.fillForm": {
    id: "browser.fillForm",
    label: "Fill Form Fields via JavaScript",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ fields: Record<string, string>, browser?: string }",
    executionPath: "planner -> intents/browser.fillForm -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
    notes: "Uses synthetic DOM events (input/change) so React/Vue controlled inputs pick up values.",
  },
  "browser.fillInput": {
    id: "browser.fillInput",
    label: "Fill Single Input Field",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ selector: string, value: string, browser?: string }",
    executionPath: "planner -> intents/browser.fillInput -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.clickElement": {
    id: "browser.clickElement",
    label: "Click DOM Element via JavaScript",
    owner: "gateway",
    status: "implemented",
    riskTier: "system-sensitive",
    inputSchema: "{ selector: string, browser?: string }",
    executionPath: "planner -> intents/browser.clickElement -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "browser.submitForm": {
    id: "browser.submitForm",
    label: "Submit Form",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ selector?: string, browser?: string }",
    executionPath: "planner -> intents/browser.submitForm -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.selectOption": {
    id: "browser.selectOption",
    label: "Select Option in Dropdown",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ selector: string, value: string, browser?: string }",
    executionPath: "planner -> intents/browser.selectOption -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getElementText": {
    id: "browser.getElementText",
    label: "Get Element Text Content",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ selector: string, browser?: string }",
    executionPath: "planner -> intents/browser.getElementText -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getElementAttribute": {
    id: "browser.getElementAttribute",
    label: "Get Element Attribute Value",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ selector: string, attribute: string, browser?: string }",
    executionPath: "planner -> intents/browser.getElementAttribute -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },

  // ─── Browser — Storage / Cookies ─────────────────────────────────────────
  "browser.clearCookies": {
    id: "browser.clearCookies",
    label: "Clear Browser Cookies",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getCookies -> browser layer (clear branch)",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Expires cookies by setting them with a past expiry date; HttpOnly cookies remain inaccessible.",
  },
  "browser.getCookies": {
    id: "browser.getCookies",
    label: "Get Browser Cookies (Non-HttpOnly)",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ domain?: string, browser?: string }",
    executionPath: "planner -> intents/browser.getCookies -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Exposes only non-HttpOnly cookies via document.cookie; HttpOnly cookies are inaccessible by design.",
  },
  "browser.getLocalStorage": {
    id: "browser.getLocalStorage",
    label: "Get localStorage Value(s)",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ key?: string, browser?: string }",
    executionPath: "planner -> intents/browser.getLocalStorage -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.setLocalStorage": {
    id: "browser.setLocalStorage",
    label: "Set localStorage Value",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ key: string, value: string, browser?: string }",
    executionPath: "planner -> intents/browser.setLocalStorage -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },

  // ─── Browser — Screenshot / PDF ───────────────────────────────────────────
  "browser.screenshot": {
    id: "browser.screenshot",
    label: "Capture Browser Screenshot",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.screenshot -> browser layer -> surface",
    verifier: "vision",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Requires SurfaceLayer to be wired; falls back to full-screen capture when browser window is not resolved.",
  },
  "browser.savePdf": {
    id: "browser.savePdf",
    label: "Save Page as PDF",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ outputPath: string, browser?: string }",
    executionPath: "planner -> intents/browser.savePdf -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Safari uses keyboard shortcut + save panel; Chrome uses --headless --print-to-pdf.",
  },

  // ─── Browser — Headless ───────────────────────────────────────────────────
  "browser.startHeadless": {
    id: "browser.startHeadless",
    label: "Start Headless Chrome/Chromium",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string, port?: number, width?: number, height?: number }",
    executionPath: "planner -> intents/browser.startHeadless -> browser layer",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Launches Chrome with remote debugging port; requires Chrome/Chromium binary to be present.",
  },
  "browser.stopHeadless": {
    id: "browser.stopHeadless",
    label: "Stop Headless Browser",
    owner: "gateway",
    status: "experimental",
    riskTier: "destructive",
    inputSchema: "{}",
    executionPath: "planner -> intents/browser.stopHeadless -> browser layer",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.isHeadlessRunning": {
    id: "browser.isHeadlessRunning",
    label: "Check Headless Browser Status",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "planner -> intents/browser.isHeadlessRunning -> browser layer",
    verifier: "process",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.executeInHeadless": {
    id: "browser.executeInHeadless",
    label: "Execute Script in Headless Browser via CDP",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ url: string, script: string }",
    executionPath: "planner -> intents/browser.executeInHeadless -> browser layer -> CDP",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Requires active headless session; depends on Python websocket-client for CDP.",
  },

  // ─── Browser — Advanced Tab ────────────────────────────────────────────────
  "browser.pinTab": {
    id: "browser.pinTab",
    label: "Pin Tab",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ tabIndex?: number, browser?: string }",
    executionPath: "planner -> intents/browser.pinTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Safari: uses keyboard shortcut; Chrome: keyboard shortcut; not natively exposed via AppleScript.",
  },
  "browser.muteTab": {
    id: "browser.muteTab",
    label: "Mute Tab Audio",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ tabIndex?: number, browser?: string }",
    executionPath: "planner -> intents/browser.muteTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome only; Safari does not support this via AppleScript.",
  },
  "browser.unmuteTab": {
    id: "browser.unmuteTab",
    label: "Unmute Tab Audio",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ tabIndex?: number, browser?: string }",
    executionPath: "planner -> intents/browser.unmuteTab -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome only; Safari does not support this via AppleScript.",
  },
  "browser.getTabMemory": {
    id: "browser.getTabMemory",
    label: "Get Per-Tab Memory Estimates",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "planner -> intents/browser.getTabMemory -> browser layer",
    verifier: "heuristic",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome only; memory is approximated from process stats even-split across open tabs.",
  },

  // ─── Browser — Downloads ────────────────────────────────────────────────────
  "browser.getDownloads": {
    id: "browser.getDownloads",
    label: "Get Browser Download History",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{ limit?: number, browser?: string }",
    executionPath: "planner -> intents/browser.getDownloads -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome: reads SQLite History DB; Safari: parses Downloads.plist.",
  },
  "browser.clearDownloads": {
    id: "browser.clearDownloads",
    label: "Clear Browser Download History",
    owner: "gateway",
    status: "experimental",
    riskTier: "destructive",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.clearDownloads -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getDownloadDirectory": {
    id: "browser.getDownloadDirectory",
    label: "Get Browser Download Directory",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.getDownloadDirectory -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },

  // ─── Browser — Bookmarks ──────────────────────────────────────────────────
  "browser.getBookmarks": {
    id: "browser.getBookmarks",
    label: "Get Browser Bookmarks",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ folder?: string, browser?: string }",
    executionPath: "planner -> intents/browser.getBookmarks -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.addBookmark": {
    id: "browser.addBookmark",
    label: "Add Bookmark",
    owner: "gateway",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ url: string, title?: string, folder?: string, browser?: string }",
    executionPath: "planner -> intents/browser.addBookmark -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome: keyboard shortcut; Safari: AppleScript make new bookmark.",
  },
  "browser.searchBookmarks": {
    id: "browser.searchBookmarks",
    label: "Search Bookmarks",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ query: string, browser?: string }",
    executionPath: "planner -> intents/browser.searchBookmarks -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.bookmark": {
    id: "browser.bookmark",
    label: "Bookmark Current Tab",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ url?: string, title?: string }",
    executionPath: "planner -> intents/browser.bookmark -> browser layer",
    verifier: "app-state",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Reads current tab URL/title via AppleScript then delegates to addBookmark.",
  },

  // ─── Browser — History / Performance ──────────────────────────────────────
  "browser.getHistory": {
    id: "browser.getHistory",
    label: "Get Browser History",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ limit?: number, since?: number, browser?: string }",
    executionPath: "planner -> intents/browser.getHistory -> browser layer",
    verifier: "file",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getPageLoadTime": {
    id: "browser.getPageLoadTime",
    label: "Get Page Load Timing Metrics",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ url?: string, browser?: string }",
    executionPath: "planner -> intents/browser.getPageLoadTime -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.getNetworkRequests": {
    id: "browser.getNetworkRequests",
    label: "Get Resource Timing Entries",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ url?: string, browser?: string }",
    executionPath: "planner -> intents/browser.getNetworkRequests -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "browser.blockUrls": {
    id: "browser.blockUrls",
    label: "Block URL Patterns via CDP (Headless)",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ patterns: string[] }",
    executionPath: "planner -> intents/browser.blockUrls -> browser layer -> CDP",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Requires active headless browser session; depends on Python websocket-client.",
  },

  // ─── Browser — Special / High-Level ───────────────────────────────────────
  "browser.scrape": {
    id: "browser.scrape",
    label: "Scrape Page Elements",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{ selector?: string, attribute?: string, browser?: string }",
    executionPath: "planner -> intents/browser.scrape -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Chrome AppleScript execute; Safari: not supported. Experimental while Safari path is evaluated.",
  },
  "browser.clickFirstVideo": {
    id: "browser.clickFirstVideo",
    label: "Open First YouTube Video",
    owner: "gateway",
    status: "experimental",
    riskTier: "reversible-write",
    inputSchema: "{ browser?: string }",
    executionPath: "planner -> intents/browser.clickFirstVideo -> browser layer",
    verifier: "dom",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Task-level E2E now exercises the planner-driven first-result path, but the dedicated browser.clickFirstVideo tool itself is not yet first-class in the shipped planner route.",
  },

  // ─── Deep macOS — Public Observability ───────────────────────────────────
  "iokit.thermals": {
    id: "iokit.thermals",
    label: "Read Thermal Sensors",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> IOKitLayer.getThermals -> smc/istats fallback",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
    notes: "Public user-space observability path; depends on available host tools such as smc or istats.",
  },
  "iokit.fans": {
    id: "iokit.fans",
    label: "Read Fan Speeds",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> IOKitLayer.getFanSpeeds -> smc/istats fallback",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
    notes: "Read-only fan telemetry only; fan write control remains experimental and out of mainline.",
  },
  "iokit.battery.health": {
    id: "iokit.battery.health",
    label: "Read Battery Health",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> IOKitLayer.getBatteryHealth -> ioreg",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "iokit.gpu": {
    id: "iokit.gpu",
    label: "Read GPU Inventory",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> IOKitLayer.getGPUInfo -> system_profiler",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.sysctl.get": {
    id: "kernel.sysctl.get",
    label: "Read sysctl Value",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ key: string }",
    executionPath: "intent registry -> KernelLayer.getSysctl -> sysctl -n",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.sysctl.all": {
    id: "kernel.sysctl.all",
    label: "Read All sysctl Values",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.getSysctlAll -> sysctl -a",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.sysctl.prefix": {
    id: "kernel.sysctl.prefix",
    label: "Read sysctl By Prefix",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{ prefix: string }",
    executionPath: "intent registry -> KernelLayer.getSysctlByPrefix -> sysctl <prefix>",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.vm.stats": {
    id: "kernel.vm.stats",
    label: "Read Virtual Memory Stats",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.getVMStats -> vm_stat",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.swap.usage": {
    id: "kernel.swap.usage",
    label: "Read Swap Usage",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.getSwapUsage -> sysctl -n vm.swapusage",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.sip.status": {
    id: "kernel.sip.status",
    label: "Read SIP Status",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.getSIPStatus -> csrutil status",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },
  "kernel.boot.args": {
    id: "kernel.boot.args",
    label: "Read Boot Arguments",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.getBootArgs -> nvram",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
    notes: "Read-only NVRAM/boot-arg visibility is allowed; mutating boot arguments is intentionally not marked implemented.",
  },
  "kernel.launchctl.list": {
    id: "kernel.launchctl.list",
    label: "List launchd Jobs",
    owner: "gateway",
    status: "implemented",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.launchctlList -> launchctl list",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "public",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: true,
    },
  },

  // ─── Deep macOS — Privileged / Experimental Control ──────────────────────
  "kernel.sysctl.set": {
    id: "kernel.sysctl.set",
    label: "Write sysctl Value",
    owner: "gateway",
    status: "flagged",
    riskTier: "system-sensitive",
    inputSchema: "{ key: string, value: string, persist?: boolean }",
    executionPath: "intent registry -> KernelLayer.setSysctl -> sudo sysctl -w",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Requires an explicit safety policy and readback verification before it can be treated as a shipped mainline action.",
  },
  "kernel.memory.purge": {
    id: "kernel.memory.purge",
    label: "Purge Inactive Memory",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.purgeMemory -> sudo purge",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
  },
  "kernel.launchctl.load": {
    id: "kernel.launchctl.load",
    label: "Load launchd Job",
    owner: "gateway",
    status: "flagged",
    riskTier: "system-sensitive",
    inputSchema: "{ plist: string }",
    executionPath: "intent registry -> KernelLayer.launchctlLoad -> launchctl load",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
  },
  "kernel.launchctl.unload": {
    id: "kernel.launchctl.unload",
    label: "Unload launchd Job",
    owner: "gateway",
    status: "flagged",
    riskTier: "destructive",
    inputSchema: "{ plist: string }",
    executionPath: "intent registry -> KernelLayer.launchctlUnload -> launchctl unload",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
  },
  "kernel.launchctl.kickstart": {
    id: "kernel.launchctl.kickstart",
    label: "Kickstart launchd Job",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ service: string }",
    executionPath: "intent registry -> KernelLayer.launchctlKickstart -> launchctl kickstart",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "privileged",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
  },
  "kernel.kext.list": {
    id: "kernel.kext.list",
    label: "List Kernel Extensions",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> KernelLayer.listKexts -> kextstat/kmutil",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: false,
    },
    notes: "Useful for diagnostics, but not a stable mainline product feature on modern macOS.",
  },
  "kernel.trace.syscalls": {
    id: "kernel.trace.syscalls",
    label: "Trace Process Syscalls",
    owner: "gateway",
    status: "flagged",
    riskTier: "system-sensitive",
    inputSchema: "{ pid: number, durationMs?: number }",
    executionPath: "intent registry -> KernelLayer.traceSyscalls -> dtruss",
    verifier: "heuristic",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Tracing depends on privileged tooling and should never be planner-routed by default.",
  },

  // ─── Security / Wi-Fi Experimental ───────────────────────────────────────
  "wifi.deep.scan": {
    id: "wifi.deep.scan",
    label: "Deep Wi-Fi Channel Scan",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{}",
    executionPath: "intent registry -> security intent -> deepOS.deepWiFiScan",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: false,
    },
    notes: "Multi-channel airport sweep; not planner-routed by default. Read-only scan surface.",
  },
  "wifi.monitor.start": {
    id: "wifi.monitor.start",
    label: "Enable Wi-Fi Monitor Mode",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ channel?: number }",
    executionPath: "intent registry -> security intent -> deepOS.enableMonitorMode",
    verifier: "process",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Requires sudo + monitor-mode driver support; not planner-routed by default.",
  },
  "wifi.monitor.stop": {
    id: "wifi.monitor.stop",
    label: "Disable Wi-Fi Monitor Mode",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{}",
    executionPath: "intent registry -> security intent -> deepOS.disableMonitorMode",
    verifier: "process",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: false,
      allowedByDefault: false,
    },
    notes: "Gracefully kills airport sniff process; not planner-routed by default.",
  },
  "wifi.channel.set": {
    id: "wifi.channel.set",
    label: "Set Wi-Fi Interface Channel",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ channel: number }",
    executionPath: "intent registry -> security intent -> deepOS.setWiFiChannel",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Requires active monitor mode; not planner-routed by default.",
  },
  "wifi.capture.handshake": {
    id: "wifi.capture.handshake",
    label: "Capture Wi-Fi Handshake Packets",
    owner: "gateway",
    status: "flagged",
    riskTier: "destructive",
    inputSchema: "{ bssid: string, channel: number, outputFile: string, durationSec?: number }",
    executionPath: "intent registry -> security intent -> deepOS.captureWiFiHandshake",
    verifier: "file",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Pentest surface. Writes .cap/.pcap output. Requires airodump-ng or tcpdump. Not planner-routed by default. Legal WARNING: Use only on networks you own or have explicit permission to test.",
  },
  "wifi.deauth": {
    id: "wifi.deauth",
    label: "Wi-Fi Deauthentication (Force Reconnection)",
    owner: "gateway",
    status: "experimental",
    riskTier: "destructive",
    inputSchema: "{ bssid: string, clientMac?: string, count?: number }",
    executionPath: "intent registry -> security intent -> deepOS.deauthAttack",
    verifier: "process",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Pentest surface requiring aireplay-ng. Not planner-routed by default. Legal WARNING: Use only on networks you own or have explicit permission to test.",
  },
  "wifi.crack.handshake": {
    id: "wifi.crack.handshake",
    label: "Crack Wi-Fi WPA Handshake via Wordlist",
    owner: "gateway",
    status: "experimental",
    riskTier: "destructive",
    inputSchema: "{ capFile: string, wordlist: string, bssid?: string }",
    executionPath: "intent registry -> security intent -> deepOS.crackWPAHandshake",
    verifier: "heuristic",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Pentest surface requiring aircrack-ng + wordlist file. Not planner-routed by default. Legal WARNING: Use only on networks you own or have explicit permission to test.",
  },
  "wifi.install-tools": {
    id: "wifi.install-tools",
    label: "Install aircrack-ng Suite via Homebrew",
    owner: "gateway",
    status: "flagged",
    riskTier: "system-sensitive",
    inputSchema: "{}",
    executionPath: "intent registry -> security intent -> deepOS.installAircrackSuite",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: false,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Installs aircrack-ng suite (airport, airodump-ng, aireplay-ng, aircrack-ng) via Homebrew; not planner-routed by default.",
  },

  // ─── Network — Experimental / Privileged ───────────────────────────────────
  "network.capture": {
    id: "network.capture",
    label: "Capture Network Packets",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ iface: string, filter: string, duration: number, outFile: string }",
    executionPath: "intent registry -> network intent -> deepOS.capturePackets",
    verifier: "file",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: true,
      requiresConfirmation: true,
      allowedByDefault: false,
    },
    notes: "Writes .pcap output; requires sudo. Not planner-routed by default.",
  },
  "network.scan.hosts": {
    id: "network.scan.hosts",
    label: "Scan Subnet for Active Hosts",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ subnet: string }",
    executionPath: "intent registry -> network intent -> deepOS.scanHosts",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: false,
    },
    notes: "Uses nmap -sn if available, falls back to arp -a. Not planner-routed by default.",
  },
  "network.scan.ports": {
    id: "network.scan.ports",
    label: "Scan Host for Open Ports",
    owner: "gateway",
    status: "experimental",
    riskTier: "system-sensitive",
    inputSchema: "{ host: string, ports?: string }",
    executionPath: "intent registry -> network intent -> deepOS.portScan",
    verifier: "api",
    observability: ["task.step", "task.complete"],
    tests: { unit: false, integration: false, e2e: false },
    policy: {
      platform: "macos",
      stability: "experimental",
      requiresPrivilege: false,
      requiresConfirmation: false,
      allowedByDefault: false,
    },
    notes: "Uses nmap -Pn if available, falls back to netcat per-port scan. Not planner-routed by default.",
  },

  // ─── UI Surface Primitives ─────────────────────────────────────────────────
  "ui.click": {
    id: "ui.click",
    label: "Pointer Click",
    owner: "native-runtime",
    status: "implemented",
    riskTier: "system-sensitive",
    inputSchema: "{ x?: number, y?: number, query?: string, button?: string }",
    executionPath: "planner -> orchestrator -> surface/ui.click",
    verifier: "vision",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "ui.type": {
    id: "ui.type",
    label: "Type Text",
    owner: "native-runtime",
    status: "implemented",
    riskTier: "reversible-write",
    inputSchema: "{ text: string }",
    executionPath: "planner -> orchestrator -> surface/ui.type",
    verifier: "vision",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
  "ui.key": {
    id: "ui.key",
    label: "Keyboard Shortcut",
    owner: "native-runtime",
    status: "implemented",
    riskTier: "system-sensitive",
    inputSchema: "{ key: string, modifiers?: string[] }",
    executionPath: "planner -> orchestrator -> surface/ui.key",
    verifier: "heuristic",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },

  // ─── System ───────────────────────────────────────────────────────────────
  "shell.exec": {
    id: "shell.exec",
    label: "Shell Execution",
    owner: "gateway",
    status: "flagged",
    riskTier: "destructive",
    inputSchema: "{ command: string }",
    executionPath: "planner -> orchestrator -> deep/shell.exec",
    verifier: "heuristic",
    observability: ["task.step", "task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
    notes: "Allowed but not considered fully typed or verification-safe.",
  },

  "unsupported.capability": {
    id: "unsupported.capability",
    label: "Honest Unsupported Capability",
    owner: "planner",
    status: "unsupported",
    riskTier: "read-only",
    inputSchema: "{ unsupportedReason: string }",
    executionPath: "planner -> unsupported node -> executor honest fail",
    verifier: "heuristic",
    observability: ["task.error", "task.complete"],
    tests: { unit: true, integration: true, e2e: true },
  },
  "verify.screenshot": {
    id: "verify.screenshot",
    label: "Screenshot Verification",
    owner: "gateway",
    status: "experimental",
    riskTier: "read-only",
    inputSchema: "{ expected: string }",
    executionPath: "executor verifyStep -> vision engine",
    verifier: "vision",
    observability: ["task.verify", "task.complete"],
    tests: { unit: true, integration: true, e2e: false },
  },
};

export const CAPABILITY_MATRIX: CapabilityMatrixEntry[] = Object.entries(CAPABILITY_CONTRACTS).map(
  ([tool, contract]) => ({
    tool,
    contractId: contract.id,
    status: contract.status,
  }),
);

const CAPABILITY_ALIASES: Record<string, string> = {
  "wifi.tools.install": "wifi.install-tools",
};

export function getCapabilityContract(tool: string): CapabilityContract | null {
  return CAPABILITY_CONTRACTS[tool] ?? CAPABILITY_CONTRACTS[CAPABILITY_ALIASES[tool] ?? ""] ?? null;
}
